### PR TITLE
Latest and greatest version of Bun.js

### PR DESCRIPTION
**Pull request by 7heMech**
Why
I really want cross platfrom compile

### CODE REVIEW

**Comment by lafkpages** [comment]
1.1.16 is out already by the way.

**Comment by lafkpages** [comment]
I can't review and you can't assign me, a collaborator has to do it.

**Review by lhchavez — APPROVED** [review]
let's see if it matters who does the approval

**Comment by cdmistman** [comment]
> Yes, this fixed the issue 🤦‍♂️
> I'm so sorry, I suspected this was the issue last time as well, strange since I fork the repo and only change needed lines might be an auto formatting on replit or something I haven't properly configured.

no worries! that's not what fixed the issue - it was fixing our GitHub Actions config in settings and https://github.com/replit/nixmodules/pull/370 :D

**Comment by cdmistman** [comment]
for context, what you pointed out is a missing newline at the end of the file (`}` was the last byte in the file, not `\n`). thanks for fixing that (it's a pet peeve of mine and i'm shocked i didn't catch it until now) but that didn't fix it :)

**Pull request merged**
